project:
  type: website
  output-dir: docs

website:
  title: "CSc 120"
  navbar:
    top:
      - href: index.qmd
        text: Home

format:
  html:
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Voltaire&display=swap" type="text/css"/>
    theme:
      light: [lux, light.scss]
      dark: [lux, dark.scss]
    css: styles.css
    toc: true
