---
title: "DIY dicts"
subtitle: "CSc 120: Introduction to Computer Programming II"
---

## Core Requirements

Handle <strong class="green">collisions</strong> in the (incorrect!) implementation from the [lecture](/hashing.qmd):

{{< include badDictCodeWithHint.qmd >}}

## Extra credit opportunities

Extra credit for <strong class="pink">creative</strong> hash functions and collision strategies\*

<small>\* Solutions that employ forms of [acceptable cheating](#acceptable-cheating) are not eligible for extra credit</small>

Things to inspect that might help:

- Look inside the `data.json` and `test.py` files; is the test code using keys in a way that you could exploit to hash quickly, and avoid collitions?
- Extra credit will be awarded separately to the most performant solution *for each type of key*. 

## Running and testing your solution 

Download and extract the [assignment](/linkNowhere.zip)

<strong class="teal">ONLY EDIT</strong> the `dictionary.py` file

To test for correctness, run `python test.py`

To test for performance, run `python benchmark.py`

<small>After the last assignment, that code should look familiar!</small>

## Acceptable cheating

As with other assignments in this course, <strong class="purple">collaboration</strong> and <strong class="pink">creative ways around the problem</strong> are encouraged!

Copypasta from Stackoverflow or AI-generated solutions are also allowed (but discouraged).

However, in all cases when you copy something you didn't write, or when you're up to something sneaky, you <strong class="orange">MUST COMMENT YOUR CODE</strong>, or you risk getting a <strong class="orange">ZERO</strong> on the assignment (fully up to the discretion of the instructor).

To stay safe, make sure that you include comments that:

- Give props about <strong class="purple">who</strong> and <strong class="purple">how</strong> specific classmates helped you
- Cite the source websites / tools that helped you, how they helped you, and for which chunks of code they helped you
- For <strong class="pink">workarounds</strong>, describe how you're avoiding the spirit of the assignment—I want to know that you know what you're doing

Also, for this assignment, any acceptable cheating will disqualify your submission for extra credit.

*Hint: It's possible to complete this assignment using the existing python `dict`, and/or ignore the `capacity` setting to achieve better performance. If your solution ignores `capacity`, you must document how / why in order to recieve credit!*

## What to submit

Upload your modified `dictionary.py` file here:

<form>
  <fieldset>
    <label for="studentId">Your student ID</label>
    <input type="text" id="studentId"/>
  </fieldset>
  <fieldset>
    <label for="extraCredit">Test my code for potential extra credit!</label>
    <input type="checkbox" id="extraCredit"/>
    <br/>
    <small class="orange">Please do NOT check this box if we'd be likely to consider your solution to be [acceptable cheating](#acceptable-cheating)</small>
  </fieldset>
  <fieldset>
    <input type="file"/>
  </fieldset>
  <fieldset>
    <button>Submit</button>
  </fieldset>
</form>

For this assignment, submit as many solutions as you like!